<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * AsociadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsociadoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Asociados a ORDER BY a.nombre ASC'
            )
            ->getResult();
    }

    public function count()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(a) FROM AppBundle:Asociados a'
            )
            ->getSingleScalarResult();
    }

    public function count_pais($pais)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('COUNT(a.idAsociado)')
            ->from('AppBundle:Asociados', 'a')
            ->where('a.pais = :pais')
            ->setParameter('pais',$pais);

        try{
            $result = $qb->getQuery()->getSingleScalarResult();
        }catch (\Doctrine\ORM\NoResultException $e){
            return false;
        }

        return $result;
    }
}
