<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * FicheroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheroRepository extends \Doctrine\ORM\EntityRepository
{

    public function count()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(f) FROM AppBundle:Fichero f WHERE f.isFolder = 0'
            )
            ->getSingleScalarResult();
    }
}
