<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * FicheroVirtualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheroVirtualRepository extends \Doctrine\ORM\EntityRepository
{
    public function count_files($year,$pais)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('COUNT(f.idFichero)')
            ->from('AppBundle:FicheroVirtual', 'f')
            ->where('YEAR(f.fechaCreacion) = :year')
            ->andWhere('f.pais = :pais')

            ->setParameter('year', $year)
            ->setParameter('pais',$pais);

        try{
            $result = $qb->getQuery()->getSingleScalarResult();
        }catch (\Doctrine\ORM\NoResultException $e){
            return false;
        }

        return $result;
    }


}
