<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends \Doctrine\ORM\EntityRepository
{


    public function count()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(p) FROM AppBundle:Proveedores p'
            )
            ->getSingleScalarResult();
    }
}
